services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=rootqwerty
      - MYSQL_DATABASE=easy_bets
      - MYSQL_USER=yard
      - MYSQL_PASSWORD=qwerty
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql